# Default values for todo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: dev
replicaCount: 1

service:
  type: ClusterIP
  name: todo-service
  port: 8081

image:
  pullPolicy: IfNotPresent
  repository: "senthilprabhut/todo-service"
  tag: "19"


autoscaling:
  enabled: false

limits:
  cpu: 2
  memory: 2Gi
requests:
  cpu: 1
  memory: 1Gi

jvmHeap: 768m

# ui service related values
ui:
  image:
    pullPolicy: IfNotPresent
    repository: "senthilprabhut/todo-ui"
    tag: "4"
  service:
    name: todo-ui
    port: 80
    backendUrl: http://localhost:4200   # ingress url

# postgres related values
postgres:
  image:
    pullPolicy: IfNotPresent
    repository: "postgres"
    tag: "12"
  service:
    name: postgres
    port: 5432
    initPath: "/tmp/k3dvol/postgresinit"
    dataPath: "/tmp/k3dvol/postgres"

# ingress related Values
ingress:
  enabled: false
  # - path: /todo/api

#   className: ""
#   annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# prometheus
prometheus:
  image:
    pullPolicy: IfNotPresent
    repository: "prom/prometheus"
    tag: "v2.24.1"
  service:
    name: prometheus
    port: 9090
