apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: {{ .Values.postgres.service.name }}
data:
  POSTGRES_DB: todo-service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
