# https://medium.com/@suyashmohan/setting-up-postgresql-database-on-kubernetes-24a2a192e962
# https://severalnines.com/database-blog/using-kubernetes-deploy-postgresql
# https://medium.com/@xcoulon/managing-pod-configuration-using-configmaps-and-secrets-in-kubernetes-93a2de9449be
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-postgres-pv
  labels:
    app: {{ .Values.postgres.service.name }}
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.service.dataPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3d-postgres-pvc
  labels:
    app: {{ .Values.postgres.service.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}-service
  labels:
    app: {{ .Values.postgres.service.name }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      name: postgresdbport
  type: NodePort
  selector:
    app: {{ .Values.postgres.service.name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: {{ .Values.postgres.service.name }}
spec:
  serviceName: {{ .Values.postgres.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.service.name }}
    spec:
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: k3d-postgres-pvc
        - name: pv-init
          configMap:
            defaultMode: 420
            name: postgres-init-config
      containers:
        - name: {{ .Values.postgres.service.name }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
              name: postgresdbport
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: pv-init
              mountPath: /docker-entrypoint-initdb.d/
            - name: pv-data
              mountPath: /var/lib/postgresql/data
