apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.serviceName }}-http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ .Values.serviceName }}
    environment: {{ .Values.environment }}
