apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    environment: {{ .Values.environment }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: DATASOURCE_URL
              value: jdbc:postgresql://postgres-service.default.svc.cluster.local:5432/$(POSTGRES_DB)
            - name: DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DATASOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: OKTA_CLIENT_ID
              value: '0oaopj8039Qtf5qQe4x6'
            - name: OKTA_CLIENT_ID
              value: '65NUzcJa0CEQzF-_EwDN8zRaW_vgKTurOQY0dW_w'
          livenessProbe:
            httpGet:
              path: /todo/api/health/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /todo/api/health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 30
          resources:
            limits:
              cpu: {{ .Values.limits.cpu }}
              memory: {{ .Values.limits.memory }}
            requests:
              cpu: {{ .Values.requests.cpu }}
              memory: {{ .Values.requests.memory }}
