apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.service.name }}
  labels:
    app: {{ .Values.ui.service.name }}
spec:
  type: ClusterIP
  ports:
  - name: ui-port
    port: {{ .Values.ui.service.port }}
  selector:
    app: {{ .Values.ui.service.name }}
