apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/rewrite-target: {{ .targetPath }}
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                 name: {{ .Values.ui.service.name }}
                 port:
                   number: {{ .Values.ui.service.port }}
          - path: /todo
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.prometheus.service.name }}
                port:
                  number: {{ .Values.prometheus.service.port }}
