apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 5s
    scrape_configs:
    - job_name: 'todo-monitoring'
      scrape_interval: 10s
      metrics_path: '/todo/api/prometheus'
      static_configs:
      - targets:
        - "{{ .Values.service.name }}.default.svc.cluster.local:{{ .Values.service.port }}"
        labels:
          app: {{ .Values.service.name }}
    - job_name: 'prometheus-monitoring'
      scrape_interval: 5s
      static_configs:
      - targets:
        - "{{ .Values.prometheus.service.name }}.default.svc.cluster.local:{{ .Values.prometheus.service.port }}"
