apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.service.name }}
  namespace: monitoring
  labels:
    app: {{ .Values.prometheus.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.prometheus.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.service.name }}
    spec:
      containers:
        - name: {{ .Values.prometheus.service.name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.external-url=/prometheus"
          ports:
            - containerPort: {{ .Values.prometheus.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
        - name: prometheus-storage-volume
          emptyDir: {}
