apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
  labels:
    app: {{ .Values.prometheus.service.name }}
  namespace: monitoring
  # annotations:
  #     prometheus.io/scrape: 'true'
  #     prometheus.io/port: {{ .Values.prometheus.service.port }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.prometheus.service.name }}-http
    port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.port }}
    nodePort: 30000
  selector:
    app: {{ .Values.prometheus.service.name }}
