apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubestate.service.name }}
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ .Values.kubestate.service.name }}
    app.kubernetes.io/version: {{ .Values.kubestate.image.tag }}
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: {{ .Values.kubestate.service.port }}
    targetPort: http-metrics
  - name: telemetry
    port: {{ .Values.kubestate.service.telemetryPort }}
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: {{ .Values.kubestate.service.name }}
