apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alertmanager.service.name }}
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: "{{ .Values.alertmanager.service.port }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.service.port }}
  selector:
    app: {{ .Values.alertmanager.service.name }}

---
# Required in the default namespace to redirect to monitoring namespace
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alertmanager.service.name }}
  labels:
    app: {{ .Values.alertmanager.service.name }}
spec:
  type: ExternalName
  externalName: {{ .Values.alertmanager.service.name }}.monitoring.svc.cluster.local
  ports:
  - port: {{ .Values.alertmanager.service.port }}
    targetPort: {{ .Values.alertmanager.service.port }}
