apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.grafana.service.name }}-http
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
  selector:
    app: grafana
---
# Required in the default namespace to redirect to monitoring namespace
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name }}
  labels:
    app: {{ .Values.grafana.service.name }}
spec:
  type: ExternalName
  externalName: {{ .Values.grafana.service.name }}.monitoring.svc.cluster.local
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: {{ .Values.grafana.service.port }}
