# SERVER
server:
  port: 8081
#  servlet:
#    context-path: /todo

# DATABASE
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/todo"
    username: postgres
    password: password

# LIQUIBASE
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml

# Logging
logging:
  level:
    org.springframework: debug