# SERVER
server:
  port: 8081
  shutdown: graceful
  servlet.context-path: /todo

# Logging
logging:
  level:
    org.springframework: info

# SHUTDOWN
spring:
  lifecycle.timeout-per-shutdown-phase: 20s

# SECURITY
  security.oauth2:
    client.registration.okta:
      authorization-grant-type: CLIENT_CREDENTIALS
      client-id: TODO_CHANGE_CLIENT_ID
      client-secret: TODO_CHANGE_CLIENT_SECRET
    resourceserver.jwt:
      # issuer-uri property points to the base Authorization Server URI (OpenID Connect discovery endpoint)
      issuer-uri: https://dev-117675.okta.com/oauth2/default
      # jwk-set-uri property contains the public key that the server can use for verifying the Token’s signature
      # jwk-set-uri: https://dev-117675.okta.com/oauth2/default/v1/keys

# DATABASE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:postgresql://localhost:5432/todo-service"
    username: postgres
    password: password
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres

  # LIQUIBASE
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog-main.xml

# ACTUATOR CONFIGURATION
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health,info
    web.base-path: /api
  endpoint:
    info.enabled: true
    health.enabled: true
    health.show-details: NEVER
    health.show-components: NEVER
    health.probes.enabled: true

management.info:
  defaults.enabled: true # Whether to enable default info contributors.
  build.enabled: false # Whether to enable build info.
  env.enabled: false # Whether to enable environment info.
  git.enabled: true # Whether to enable git properties
  git.mode: SIMPLE

# FRAMEWORK CONFIGURATION
sbf:
  okta.auth:
    enable-oauth2: false
    permit-all-paths: /,/api/health/**,/api/info