# https://www.techiediaries.com/github-actions-install-nodejs-angular-cli-deploy-github-pages/

name: Todo UI - Build Angular Code, Publish Docker Image

on:
  push:
    paths:
    - "todo-ui/**"

jobs:
  build:
    name: Build source code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm install --force
    - name: Build
      run: npm run build

    # - name: Publish generated content to GitHub Pages
    #   uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
    #   with:
    #       dir: dist
    #       branch: gh-pages
    #       token: ${{ secrets.ACCESS_TOKEN }}

  # Needs DOCKER_USER and DOCKER_PASSWORD secrets to be set in GitHub
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    env:
      DOCKER_REGISTRY_URL: "docker.io"
    defaults:
      run:
        working-directory: ./todo-ui

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1 #this will install Node and npm on Ubuntu
        with:
          node-version: '16.x'
      - name: Build and push the images
        run: |
            DOCKERFILE_PATH=Dockerfile
            DOCKER_IMAGE=$DOCKER_REGISTRY_URL/${{ secrets.DOCKER_USER }}/todo-ui

            VERSION="${{ github.run_number }}"
            BRANCH="${{ github.ref }}"
            COMMIT_ID="${{ github.sha }}"
            COMMIT_MSG="${{ github.event.head_commit.message }}"
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            echo docker build --file $DOCKERFILE_PATH --tag $DOCKER_IMAGE:latest --build-arg BRANCH=$BRANCH --build-arg COMMIT_ID=$COMMIT_ID --build-arg COMMIT_MSG="$COMMIT_MSG" --build-arg CREATED=$BUILD_DATE --build-arg VERSION=$VERSION .
            docker build --file $DOCKERFILE_PATH --tag $DOCKER_IMAGE:latest --build-arg BRANCH=$BRANCH --build-arg COMMIT_ID=$COMMIT_ID --build-arg COMMIT_MSG="$COMMIT_MSG" --build-arg CREATED=$BUILD_DATE --build-arg VERSION=$VERSION .

            docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$VERSION
            docker push $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:$VERSION
